name: Build Yuzu with Make

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Using Linux for Make

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Generate Makefile
      run: |
        mkdir build
        cd build
        cmake .. -G "Unix Makefiles"

    - name: Compile with Make
      run: |
        cd build
        make -j$(nproc)

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: yuzu-build
        path: build/
